POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Dominando o Docker"
}

###
GET http://localhost:3333/courses
###
GET http://localhost:3333/courses/591921c3-4614-4dea-b78c-ee1936049d5d
