POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNmFiNTIzOS0yMGI4LTRiMjEtYTJiNS03MDQzMTFmOWI0YTMiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc2NTA0NDQ1N30.SYPm67DVuq5XyqjJb115bDi-MexsUVrpQIQvjX_oaWQ

{
  "title": "Curos de React-Native MANAGER SENIOR"
}

###
GET http://localhost:3333/courses?orderBy=title
###
GET http://localhost:3333/courses/97814cdf-1972-495b-af18-4c1c34f92fce
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNmFiNTIzOS0yMGI4LTRiMjEtYTJiNS03MDQzMTFmOWI0YTMiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc2NTA0MjY2OH0.5tP9360lv36_7Gvi0QtsM5MZNBvvfwtZ-NeNnQ7gBR0
###
POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Paulo.Macedo@yahoo.com",
  "password": "123456"
}
